FROM node:14

ENV GRAPHQL_URL=http://localhost:1337/graphql
ENV ENABLE_GATSBY_REFRESH_ENDPOINT=true

WORKDIR /usr/src
COPY . .
RUN npm install
RUN npm install gatsby-cli -g
EXPOSE 8000

CMD ["gatsby", "develop", "-H", "0.0.0.0"]

